# Generated by Django 5.2.7 on 2025-10-31 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('приложение', '0003_аватарка'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='аватарка',
            options={'verbose_name': 'Аватарка', 'verbose_name_plural': 'Аватарки'},
        ),
    ]
